#adapted from example in docker documentation
version: '3'

services:
  web:
    build: .
   #  image: registry.gitlab.com/csuchico/csuc-cins465/cins465-f19-examples:latest
    volumes:
       - .:/code
    ports:
       - 8000:8000
    # user: "1000:1000"
    command: python /code/mysite/manage.py runserver 0.0.0.0:8000
