# Generated by Django 2.2.5 on 2019-09-19 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_suggestion_suggestion2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='suggestion2',
        ),
    ]
