# Generated by Django 2.2.5 on 2019-10-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20191008_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='image',
            field=models.ImageField(default='', max_length=144, upload_to='uploads/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suggestion',
            name='image_description',
            field=models.CharField(default='', max_length=240),
            preserve_default=False,
        ),
    ]
